Implemented HRAB algorithm
SwarmForm/SwarmForm pull request #25
Opened 2020-10-21 16:23 UTC by rpjayasekara

2020-10-22 05:29 UTC, KalanaDananjaya approved these changes

2020-10-24 10:35 UTC, AyeshW requested changes
Let's try to return outputs as same as WPA for minimizing further issues

2020-10-24 10:35 UTC, AyeshW commented on swarmform/core/clustering_algo/hrab_clustering.py
> +def get_sum_0f_exec_time(cluster):
change function name to ```get_sum_of_exec_time``` and refactor

2020-10-24 10:35 UTC, AyeshW commented on swarmform/core/clustering_algo/hrab_clustering.py
> +def cluster_wf(workflow, cluster_num):
suggestion: rename function name to 'rac_clustering' as same as 'wpa_clustering'

2020-10-24 10:35 UTC, AyeshW commented on swarmform/core/clustering_algo/hrab_clustering.py
> +def cluster_wf(workflow, cluster_num):
+ add a docstring

2020-10-24 10:35 UTC, AyeshW commented on swarmform/core/clustering_algo/hrab_clustering.py
> +
return 'workflow' similar to WPA

2020-10-24 10:35 UTC, AyeshW commented on swarmform/core/clustering_algo/hrab_clustering.py
> +        fw_info = {'exec_time': runtime, 'cores': 5}
replace static value

2020-10-24 10:35 UTC, AyeshW commented on swarmform/core/clustering_algo/hrab_clustering.py
> +cluster_wf(sf_dag, 3)
remove at the end

2020-10-24 15:40 UTC, AyeshW approved these changes
Ready to be merged

2020-10-24 15:40 UTC, merged